### ISSUE TITLE
Scraping is slower than expected :\

### ISSUE THREAD

**Issue by ghost** [foxt451/actor-quora-scraper#4]
First of all, thank you for the great work you did (and doing) with this scraper.
Truly great work.
I'm running the scraper using `Apify`
This is the input
```
{
  "proxy": {
    "useApifyProxy": true,
    "apifyProxyCountry": "US"
  },
  "query": "why"
}
```
And this is its current state:
![image](https://user-images.githubusercontent.com/38460810/208857362-d29a61da-4729-4b67-8434-bc0c3ec28815.png)

I'm wondering why it's much slower than what you stated in the README.
Do you have any idea?

**Comment by ghost** [comment]
@foxt451 Do you want to work on this together?

**Comment by foxt451** [comment]
@igaloly Yeah, that'd be cool. I won't have too much time debugging this, but I'll try to take a look this evening.

**Comment by foxt451** [comment]
@igaloly I have spent some hours on this. Things I have changed that could impact performance:
1) now for storing answers I use a separate class that reacts to persistState event. This allows to only persist answers every minute or so as it is needed instead of after every request to answers endpoint. This also apparently solved a bug when a question with hundreds of answers would eventually only get 30-50 stored (I'm pretty sure this bug used to be present).
2) this crawler used to get new proxy url for each request, now it only gets one upon session initialization and later gets reused.

Now let's compare how fast it is. First of all, you should note that for this query "why", 1340 results (questions) will entail 9.9 crawler requests (this is from my last run after these changes). I guess it's because this query allows for selection of very popular questions that gather thousands (really) of answers and you have to make a lot of requests for each question. Questions are gathered in batches of 10 (I'd like to increase it, but for questions endpoint, API ignores this parameter :( ). So 1340 results means 134 requests for questions, leaving about 9766 other requests for answers. Answers are fetched in batches of 100. So, on average 728 answer for each question (give or take, answers endpoint will return some additional garbage, so for an actual 100 batch you may need 2-3 requests; plus, last page might be often almost empty). In contrast, the run I provided in README  with 698 questions only made a total of 780 requests and ran for 3.5 mins (it ran before these changes). Let's calc the ratio. "why" 206 requests per minute vs README 222 per minute. Pretty similar, I think. Also, after the changes it managed to get 1370 results after 50 minutes vs 1450 after 1 hour before changes. Not a big difference I guess.

I see potential ways for improvement: currently, I keep a separate file for each question's answers. This resulted about 4388 KV writes (i.e. API calls) for 50 minute run. I guess I might combine answer results all in one file or try some other approach to reduce this number. Also, I could enable batch customization to allow fetching e.g. 1000 answers at a time, thus potentially reducing 9766 answer requests to only 1000 or so.

If you have ideas where are other bottlenecks, I'll listen to your ideas

**Comment by ghost** [comment]
@foxt451 Your investigation is great.
When I tried to run in locally without a proxy, after 10 questions I got blocked.
So, it seems like this method requires a proxy.
I think in the majority of cases - limiting the number of crawled answers to the top 50 is more than enough (sorted by upvotes). It might be safe to assume that the 1385's answer is pretty similar to the other ones and does not add any viable information.
Moreover, I think that there should be 2 crawling types - one for search queries and one for Feeds. I investigated and saw that there's an endpoint that fetches feed items and is pretty similar to the query one.
We might utilize Promise.all / multi-threading to run multiple queries at the same time to improve performance.
The current way of saving answers is a bit problematic in Apify because there's no ability to download all the answers in a key-value store. You need to go through them one by one.
The data structures you currently save in seem to be pretty fine and I don't think more optimization is needed there.

**Comment by ghost** [comment]
@foxt451 As i see it now, it is possible to utilize the `Get list of keys` endpoint to recieve all the key-value store keys and then download them one by one via the `Get record` endpoint. I think it's pretty fine :)

**Comment by ghost** [comment]
I did some modifications:
main.ts - to make it run locally
![image](https://user-images.githubusercontent.com/38460810/209460607-ecf61dad-c94d-4c5f-b63b-1cabb6824c64.png)

routes.ts
Quora puts null in the `after` field. Get only 20 comments - no need for more
![image](https://user-images.githubusercontent.com/38460810/209460622-f672bfc6-d5f9-4a77-965a-88519bdb435f.png)
Moreover, because we take only 20 comments, this is not needed
![image](https://user-images.githubusercontent.com/38460810/209460643-3ff6678f-30cc-4be8-93af-76cc329161c2.png)

query_arguments.ts
fetch by upvotes
![image](https://user-images.githubusercontent.com/38460810/209460649-3ab29be4-2e54-47a2-a488-9ed3a5c44407.png)

**Comment by ghost** [comment]
@foxt451 I scraped almost 2000 questions quickly. With utilizing the event loop better (promise.all) we can make this super fast.
My previous statement about the Proxy is incorrect. I ran it locally without a proxy and it worked great.
I think we should:
1. Add a parameter for the sorting of the answers. Upvote count by default
2. Add parameter to answers limit. null by default with means all of the answers
3. Make sure the pagination variable is aligned with the answers count limit
4. Add an option to crawl a feed (it can also be a quora space / topic) instead of only a search query. As I saw, it is a different endpoint but the returned data structure is almost the same

**Comment by ghost** [comment]
@foxt451 
I'm happy to announce that after some modificaitons, I was able to scrape almost 100k from my local machine easily.
I will fork your repo and submit my changes there

**Comment by ghost** [comment]
@foxt451 
BTW, there's an issue with the GC in the project. It is connected with the AnswerStore / Dataset store.
The run becomes slower and slower util there's a memory error. Unfortunately i didn't record that.

**Comment by ghost** [comment]
@foxt451 
This is mine Quora scraping repo. It is a clone from your. Please go through it to have an idea of what I did there :)
https://github.com/igaloly/quo-scr

**Comment by ghost** [comment]
@foxt451 
I'm `loly#5506` in discord. Add me and lets chat a bit :)

**Comment by foxt451** [comment]
@igaloly very cool, I've got a message for you in Discord, please add me to friends
